# Generated by Django 3.2.4 on 2021-06-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComparacionFrutas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_comparacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'comparacion_frutas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadisticaGenero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_calculo', models.DateTimeField()),
                ('porcentaje_ranking3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking_neg3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking_neg2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking_neg1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_no_probado3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_no_probado2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_no_probado1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'estadistica_genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadisticaGlobal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_calculo', models.DateTimeField()),
                ('total_frutas', models.IntegerField()),
                ('porcentaje_ranking3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_ranking_neg3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking_neg2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking_neg1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_no_probado3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_no_probado2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_no_probado1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'estadistica_global',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadisticaRegion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_calculo', models.DateTimeField()),
                ('porcentaje_ranking3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking_neg3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking_neg2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_ranking_neg1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_no_probado3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_no_probado2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_no_probado1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'estadistica_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadisticaRegionGenero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_calculo', models.DateTimeField()),
                ('total_frutas', models.IntegerField()),
                ('porcentaje_ranking3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('porcentaje_ranking2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('porcentaje_ranking1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('porcentaje_ranking_neg3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('porcentaje_ranking_neg2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('porcentaje_ranking_neg1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('porcentaje_no_probado3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('porcentaje_no_probado2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('porcentaje_no_probado1', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'estadistica_region_genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoFruta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'estado_fruta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=500)),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'fruta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogFrutas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('accion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'log_frutas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogUsuarios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('accion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'log_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreferenciasFrutas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ranking_valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'preferencias_frutas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sabor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'sabor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UltimaPreferencia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ultima_preferencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('passwrd', models.CharField(max_length=20)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('imagen_avatar', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
